# Entrypoints to connect to the gossip network (required)
entrypoints = [
    "entrypoint.devnet.solana.com:8001",
    "entrypoint2.devnet.solana.com:8001",
    "entrypoint3.devnet.solana.com:8001",
    "entrypoint4.devnet.solana.com:8001",
    "entrypoint5.devnet.solana.com:8001",
]

# Genesis hash (required)
genesis_hash = "EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG"

# Storage server (required)
storage_server = "https://your-storage-server.com"

# Optional: Bind address for RPC (default: 0.0.0.0:8899)
#rpc_listen: 127.0.0.1:8899

# Optional: Path to keypair file (default: keypair.json)
#keypair_path = "my-keypair.json"

# Optional: Public IP address (default: use STUN)
#public_addr = 1.2.3.4

# Optional: STUN server (default: stun.l.google.com:3478)
#stun_server = 1.2.3.4:3478

# Optional: Enable upnp (default: false)
#enable_upnp = true
