# Solana Snapshot Delivery Network (SSDN) Gossip Client Configuration
#
# See /usr/share/doc/agave-snapshot-gossip-client/example-config.toml
#
# If this file is not present, we will generate a new one every time we are run.
keypair_path = "/etc/gossip-client/keypair.json"

# Disable gossip until ready. The defaults ships this way to prevent joining the gossip network when newly installed.
disable_gossip = true

# You must configure this or nothing will work, unless you intend to serve local files here
#storage_path = "https://your.storage.server.com"
storage_path = "/var/www"
