name: Build

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - 'Dockerfile'
      - '.dockerignore'
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'  # Ignore version tags
    paths:
      - '.github/workflows/**'
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - 'debian/**'
      - 'Dockerfile'
      - '.dockerignore'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    uses: ./.github/workflows/build-common.yml
    with:
      upload_artifacts: true
      verify_version: true

  docker:
    needs: build
    if: |
      !failure() && !cancelled() &&
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository)
    uses: ./.github/workflows/docker.yml
    permissions:
      contents: read
      packages: write

  debian:
    needs: build
    if: |
      !failure() && !cancelled() &&
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository)
    uses: ./.github/workflows/debian.yml
    permissions:
      contents: read
      packages: write

  test-debian:
    name: Test Debian Package
    needs: [debian]
    if: | # Condition to run only if dependency succeeded
      !failure() && !cancelled() &&
      needs.debian.result == 'success'
    permissions:
      contents: read
      actions: read # Needed for download-artifact in test-debian
    uses: ./.github/workflows/test-debian.yml

  test-docker:
    name: Test Docker Image
    needs: [docker]
    if: | # Condition to run only if dependency succeeded
      !failure() && !cancelled() &&
      needs.docker.result == 'success'
    permissions:
      contents: read
      packages: read # Needed for docker pull in test-docker
      actions: read # Potentially needed if docker tests download artifacts
    uses: ./.github/workflows/test-docker.yml
    with:
      head_sha: ${{ github.sha }} # Pass the commit SHA
      repo_full_name: ${{ github.repository }} # Pass the repository name
    # NOTE: secrets are not passed by default, but GITHUB_TOKEN has packages: read permission here

permissions:
  contents: read
