name: Build

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'  # Ignore version tags
    paths:
      - '.github/workflows/**'
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    uses: ./.github/workflows/build-common.yml
    with:
      upload_artifacts: true
      verify_version: true

  docker:
    needs: build
    if: |
      !failure() && !cancelled() &&
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository)
    uses: ./.github/workflows/docker.yml
    permissions:
      contents: read
      packages: write

  debian:
    needs: build
    if: |
      !failure() && !cancelled() &&
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository)
    uses: ./.github/workflows/debian.yml
    permissions:
      contents: read
      packages: write

permissions:
  contents: read
