name: Build Trigger

on:
  workflow_call:
    inputs:
      workflow_id:
        type: string
        required: true
        description: 'The workflow to trigger'

jobs:
  trigger:
    name: Trigger ${{ inputs.workflow_id }}
    runs-on: ubuntu-22.04
    steps:
      - name: No-op
        run: echo "Triggering ${{ inputs.workflow_id }}"
