name: Invalidate Cache

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for invalidating cache'
        required: true
        default: 'Manual cache invalidation'

jobs:
  invalidate:
    name: Invalidate Cache
    runs-on: ubuntu-latest
    steps:
      - name: Invalidate Cache
        uses: actions/cache/delete@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-cache 
