name: PR Build

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '.github/workflows/**'
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'  # Ignore version tags
    paths:
      - '.github/workflows/**'
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  build:
    uses: ./.github/workflows/build-common.yml
    with:
      upload_artifacts: false
      verify_version: true
