name: PR Build

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'  # Ignore version tags

jobs:
  build:
    uses: ./.github/workflows/build-common.yml
    with:
      upload_artifacts: false
      verify_version: true
